---
galaxy_info:
  author: Johan
  description: Install Firefox from Flathub and remove Firefox ESR
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Debian
      versions:
        - all

dependencies:
  - role: flatpak
