---
galaxy_info:
  author: Johan
  description: Manage APT sources.list for Debian 13
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Debian
      versions:
        - all

dependencies: []
